<x-dynamic-component 
    component="filament::modal.index" 
    :alignment="$alignment ?? null"
    :ariaLabelledby="$ariaLabelledby ?? null"
    :autofocus="$autofocus ?? null"
    :closeButton="$closeButton ?? null"
    :closeByClickingAway="$closeByClickingAway ?? null"
    :closeByEscaping="$closeByEscaping ?? null"
    :closeEventName="$closeEventName ?? null"
    :closeQuietlyEventName="$closeQuietlyEventName ?? null"
    :description="$description ?? null"
    :extraModalWindowAttributeBag="$extraModalWindowAttributeBag ?? null"
    :footer="$footer ?? null"
    :footerActions="$footerActions ?? null"
    :footerActionsAlignment="$footerActionsAlignment ?? null"
    :header="$header ?? null"
    :heading="$heading ?? null"
    :icon="$icon ?? null"
    :iconAlias="$iconAlias ?? null"
    :iconColor="$iconColor ?? null"
    :id="$id ?? null"
    :openEventName="$openEventName ?? null"
    :slideOver="$slideOver ?? null"
    :stickyFooter="$stickyFooter ?? null"
    :stickyHeader="$stickyHeader ?? null"
    :trigger="$trigger ?? null"
    :visible="$visible ?? null"
    :width="$width ?? null"
    :attributes="\Filament\Support\prepare_inherited_attributes($attributes)"
>
    {{ $slot }}
</x-dynamic-component>